version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
       - "5672:5672"
       - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  authservice:
    build: ./authservice
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGODB_URL=mongodb+srv://pradeepkumarbgs62019:pradeep123@cluster0.b6pagz4.mongodb.net/devTube
      - ACCESS_TOKEN_SECRET=chai-aur-code
      - ACCESS_TOKEN_EXPIRY=10d
      - REFRESH_TOKEN_SECRET=chai-aur-backend
      - REFRESH_TOKEN_EXPIRY=10d
      - CLOUDINARY_CLOUD_NAME=dpgiybkjb
      - CLOUDINARY_API_KEY=942296744429925
      - CLOUDINARY_API_SECRET=Tu289hKRVlIuNKTAJItcG4ekUBo
    depends_on:
      - rabbitmq

  videouploadservice:
    build: ./videoUploadService
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGODB_URL=mongodb+srv://pradeepkumarbgs62019:pradeep123@cluster0.b6pagz4.mongodb.net/
      - DATABASE_NAME=devTube
      - CLOUDINARY_CLOUD_NAME=dpgiybkjb
      - CLOUDINARY_API_KEY=942296744429925
      - CLOUDINARY_API_SECRET=Tu289hKRVlIuNKTAJItcG4ekUBo
      - ACCESS_TOKEN_SECRET=chai-aur-code
    depends_on:
      - rabbitmq

  devtube-node:
    build: ./devtube-node
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URL=mongodb+srv://pradeepkumarbgs62019:pradeep123@cluster0.b6pagz4.mongodb.net/
      - ACCESS_TOKEN_SECRET=chai-aur-code
      - ACCESS_TOKEN_EXPIRY=10d
      - REFRESH_TOKEN_SECRET=chai-aur-backend
      - REFRESH_TOKEN_EXPIRY=10d
      - CLOUDINARY_CLOUD_NAME=dpgiybkjb
      - CLOUDINARY_API_KEY=942296744429925
      - CLOUDINARY_API_SECRET=Tu289hKRVlIuNKTAJItcG4ekUBo
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx-api-gateway.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
